###
get http://localhost:8080/api/languages/english

###
get http://localhost:8080/api/languages/swedish


###
POST http://localhost:8080/api/languages/english
Content-Type: application/json

{ "english": "cat", "finnish": "kissa" }

###
POST http://localhost:8080/api/languages/swedish
Content-Type: application/json

{ "swedish": "hund", "finnish": "koira" }


// VALIDATION REQUESTS

###
POST http://localhost:8080/api/languages/english/validate/1
Content-Type: application/json

{ "finnish": "KOIRA" }

###
POST http://localhost:8080/api/languages/swedish/validate/1
Content-Type: application/json

{ "finnish": "koira" }