###
get http://localhost:8080/api/languages/english

###
get http://localhost:8080/api/languages/swedish


###
POST http://localhost:8080/api/languages/english
Content-Type: application/json

{ "english": "cat", "finnish": "kissa" }

###
POST http://localhost:8080/api/languages/swedish
Content-Type: application/json

{ "swedish": "katt", "finnish": "kissa" }